### ISSUE TITLE
aptmak Mod-Blue

### ISSUE THREAD

**Issue by moosylog** [Apsu/aptmak#1]
No issue, but some feedback.

Thank you for creating aptmak! 
Aptmak Mod-Blue introduces several modifications to Apsu's Aptmak keyboard layout, enhancing typing comfort for bilingual English-Dutch users. Originally created by Moosy in early 2024, Mod-Blue is commonly referred to as Aptmak Blue.

The word 'blue' in Japanese is 'aoi,' which corresponds to the first three letters of the modified left home row, pronounced approximately as ah-oh-ee.

While Aptmak is an excellent layout for English, Blue adjusts the placement of a few keys to improve the typing experience for both English and Dutch users more effectively.

```
q j u l ;    b p f w x

a o i n y    k h t s r '

z . , m      v d g c / 

        e    spc
```
        
        
explained:
https://sites.google.com/view/keyboards/layout/aptmak-blue

**Comment by Apsu** [comment]
Thanks for the appreciation and the link! Looks like you did a lot of good research, your English + Dutch variation is very interesting. Designing layouts can be very challenging but is a lot of fun. I hope it works well for your needs!
